[package]
name = "agg"
version = "1.4.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
avt = { git = "https://github.com/asciinema/avt.git", tag = "v0.6.0" }
clap = { version = "3.2.15", features = ["derive"] }
env_logger = "0.10"
fontdb = "0.10"
fontdue = "0.7"
gifski = "1"
imgref = "1"
log = "0.4"
reqwest = { version = "0.11.11", default-features = false, features = ["blocking", "rustls-tls", "gzip"] }
resvg = { version = "0.28", features = ["text"] }
rgb = "0.8"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
shellexpand = "3.1.0"
tiny-skia = "0.8.3"
usvg = "0.28.0"
